### ISSUE TITLE
Any useful scripts for automating / helpful scripts 

### ISSUE THREAD

**Issue by ghost** [sonuishaq67/linuxscripts#3]
Making new scripts for linux users 
related to cron jobs etc
If its distro/DE specific label them accordingly in the folders

Any language is cool !
I used shell cause it was easier 

**Please do comment before you send a pr**

**Comment by kvaps** [comment]
HI, it seems you're collecting useful stuff here, I glad to see that project participating Hacktoberfest event :-)

I have few cool onliners to contribute if you want to:
- this one to translate selected text and send it to system notifications [[here](https://github.com/kvaps/dotfiles/blob/868c945752fa3ef8d02aabdee0789398afac6ecb/awesome/.config/awesome/rc.lua#L294-L295)]
- uses [xcwd](https://github.com/schischi/xcwd) to spawn terminal window in same place than focused one [[here](https://github.com/kvaps/dotfiles/blob/868c945752fa3ef8d02aabdee0789398afac6ecb/awesome/.config/awesome/rc.lua#L310)]

also [autorandr](https://github.com/phillipberndt/autorandr) is quite nice piece of software, I have not specific scripts for it, it working find by itself.

**Comment by sonuishaq67** [comment]
thanks @kvaps 
ill add anything useful to the repo's

**Comment by sonuishaq67** [comment]
meanwhile if you have any scripts you use to make stuff easier you can add them here
